server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: member
          uri: http://localhost:8082
          predicates:
            - Path=/members/**, 
        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**, 
        - id: test11
          uri: http://localhost:8084
          predicates:
            - Path=/undefined/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: test11
          uri: http://test11:8080
          predicates:
            - Path=/undefined/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
